In [1]:
#Objective: The objective of this assignment is to gain practical experience with fundamental operations in TensorFlow, including creating and manipulating matrices, performing arithmetic operations on tensors, and understanding the difference between TensorFlow constants and variables.

In [2]:
#Part I: Theoretical Questions

#1. What are the different data structures used in Tensorflow?. Give some examples.

#Ans

#TensorFlow primarily uses two fundamental data structures for representing data: tensors and graphs.

#1 - Tensors:

#Tensor: A tensor is a multi-dimensional array that can hold data of various types (e.g., float32, int64). Tensors are the basic building blocks in TensorFlow and can have different ranks (0D scalar, 1D vector, 2D matrix, etc.).

#tensor = tf.constant([1, 2, 3])  # Example of a 1D tensor

#2 - Graphs:

#Computational Graph: TensorFlow uses a computational graph to represent a sequence of operations as a directed graph. In this graph, nodes represent operations, and edges represent data (tensors) flowing between these operations.
#Example: When you define a series of operations using TensorFlow, it creates a graph to represent these operations. For instance:

#a = tf.constant(2)
#b = tf.constant(3)
#c = tf.add(a, b)

#In this example, a computational graph is created with nodes representing constants and the addition operation.
#In addition to these fundamental structures, TensorFlow provides other data structures and abstractions for specific use cases, such as:


#1 - Variables:

#tf.Variable: TensorFlow provides a special type of tensor called a variable, which is used to represent trainable parameters in machine learning models. Variables can be updated during training.

#dataset = tf.data.Dataset.from_tensor_slices((features, labels))

#2 - Datasets:

#tf.data.Dataset: TensorFlow provides the tf.data.Dataset API for efficiently managing and processing large datasets. It allows you to create data pipelines for input data into machine learning models.

#dataset = tf.data.Dataset.from_tensor_slices((features, labels))

#3 - Sparse Tensors:

#tf.sparse.SparseTensor: Sparse tensors are used when dealing with sparse data, where most of the elements are zero. They are represented more efficiently than dense tensors.

#indices = tf.constant([[0, 0], [1, 2]])
#values = tf.constant([1.0, 2.0])
#sparse_tensor = tf.sparse.SparseTensor(indices, values, dense_shape=[3, 4])

#4 -  Ragged Tensors:

#tf.RaggedTensor: Ragged tensors are used to represent sequences of tensors with varying lengths, which can be common in natural language processing tasks.

#ragged_tensor = tf.ragged.constant([[1, 2, 3], [4, 5], [6, 7, 8, 9]])

#5 - String Tensors:

#tf.string: TensorFlow provides data structures for handling string data, as text data is prevalent in many machine learning applications.

#text_tensor = tf.constant("Hello, TensorFlow!")

In [3]:
#2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.

#Ans

#The main difference between TensorFlow constants and TensorFlow variables is that constants hold fixed values that do not change during computation, while variables can hold values that can be updated during training.

#TensorFlow Constant:

#Holds a fixed value throughout the computation.

#Example:

#constant_tensor = tf.constant([1, 2, 3])

#TensorFlow Variable:

#Represents trainable parameters in machine learning models.
#Values can be updated during training using gradient descent or other optimization algorithms.

#Example:

#initial_value = tf.constant([4, 5, 6])
#variable_tensor = tf.Variable(initial_value)

#In the example with the constant, the values [1, 2, 3] remain fixed, whereas in the example with the variable, you can update the values of variable_tensor during training to optimize a machine learning model.

In [4]:
#3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.

#Ans

#Matrix Addition in TensorFlow:

#Matrix addition is performed using the + operator or the tf.add() function.

#Example:

#matrix1 = tf.constant([[1, 2], [3, 4]])
#matrix2 = tf.constant([[5, 6], [7, 8]])
#result_matrix_add = matrix1 + matrix2  # or tf.add(matrix1, matrix2)

#Matrix Multiplication in TensorFlow:

#Matrix multiplication is performed using the tf.matmul() function or the @ operator in Python 3.5+.

#Example:

#matrix1 = tf.constant([[1, 2], [3, 4]])
#matrix2 = tf.constant([[5, 6], [7, 8]])
#result_matrix_mul = tf.matmul(matrix1, matrix2)  # or matrix1 @ matrix2

#Element-Wise Operations in TensorFlow:

#Element-wise operations are applied to corresponding elements of two tensors of the same shape.

#Examples:

#Element-wise addition:

#tensor1 = tf.constant([1, 2, 3])
#tensor2 = tf.constant([4, 5, 6])
#result_add = tensor1 + tensor2  # Element-wise addition

#Element-wise multiplication:

#tensor1 = tf.constant([1, 2, 3])
#tensor2 = tf.constant([4, 5, 6])
#result_mul = tf.multiply(tensor1, tensor2)  # Element-wise multiplication

#These operations are fundamental for performing mathematical computations with tensors in TensorFlow, and they can be used in various machine learning and deep learning algorithms.

In [5]:
#Part 2: Practical Implementation

#Task 1: Creating and Manipulating Matrices

#1. Create a normal matrix A with dimensions 3x3, using TensorFlow's random _normal function. Display the values of matrix A.

import tensorflow as tf

# Create a 3x3 matrix with random values sampled from a normal distribution
A = tf.random.normal(shape=(3, 3))

# Display the values of matrix A
print("Matrix A:")
print(A.numpy())

Matrix A:
[[-0.30780762 -0.91032255  2.4189017 ]
 [-0.16970913  0.89692223  0.8648318 ]
 [-0.8581853   1.1099262  -0.38195327]]


In [6]:
#2. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated _normal function. Display the values of matrix B.

#Ans

import tensorflow as tf

# Create a 4x4 matrix with random values sampled from a truncated normal distribution
B = tf.random.truncated_normal(shape=(4, 4))

# Display the values of matrix B
print("Matrix B:")
print(B.numpy())

Matrix B:
[[ 1.2633842  -0.63729167 -0.42928985 -1.0818102 ]
 [ 0.40672553 -0.6456669  -0.3641784   1.1365311 ]
 [-0.6958293  -0.33149314  0.52005833  1.1426545 ]
 [-0.33280784 -0.29085645  1.4807286  -0.22685386]]


In [7]:
#3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.

#Ans

import tensorflow as tf

# Specify mean and standard deviation
mean = 3.0
stddev = 0.5

# Create a 2x2 matrix with random values sampled from a normal distribution with the specified mean and standard deviation
C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev)

# Display the values of matrix C
print("Matrix C:")
print(C.numpy())

Matrix C:
[[3.0084033 2.3498826]
 [3.3297052 3.0665457]]


In [8]:
#4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.

#Ans

import tensorflow as tf

# Create matrix A (3x3) and matrix B (4x4)
A = tf.random.normal(shape=(3, 3))
B = tf.random.truncated_normal(shape=(4, 4))

# Perform matrix addition
# Since the dimensions don't match, you need to make them compatible first.
# Let's add zeros to A to make its dimensions match with B, and then perform addition.
A_padded = tf.pad(A, paddings=[[0, 1], [0, 1]])  # Pad A with zeros to match dimensions with B
D = A_padded + B  # Perform matrix addition

# Display matrix D
print("Matrix D (Result of Addition):")
print(D.numpy())

Matrix D (Result of Addition):
[[-0.44306755 -0.39043915 -1.4643936  -1.4058896 ]
 [ 1.7352654   0.5758469  -0.13015234  0.1113697 ]
 [ 2.4327598  -0.1781295  -0.13044353  0.8875616 ]
 [-1.8838873   1.3613546   1.5595969   0.39293748]]


In [10]:
#5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

#Ans

import tensorflow as tf

# Create matrix C (2x2) and matrix D (4x4)
C = tf.random.normal(shape=(2, 2), mean=3.0, stddev=0.5)

# Assuming we have previously created matrix D as shown in the previous response

# Pad matrix C with zeros to match dimensions with D
C_padded = tf.pad(C, paddings=[[0, 2], [0, 2]])  # Pad C with zeros to match dimensions with D

# Perform matrix multiplication
E = tf.matmul(C_padded, D)

# Display matrix E
print("Matrix E (Result of Multiplication):")
print(E.numpy())

Matrix E (Result of Multiplication):
[[ 2.7128441   0.179663   -4.637105   -3.903757  ]
 [ 2.6596546   0.07022759 -5.1978426  -4.426583  ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]


In [11]:
#Task 2: Performing Additional Matrix Operations

#1. Create a matrix F with dimensions 3x3, initialized with random values using TensorFlow's random _uniform function.

#Ans

import tensorflow as tf

# Create a 3x3 matrix with random values sampled from a uniform distribution
F = tf.random.uniform(shape=(3, 3))

# Display the values of matrix F
print("Matrix F:")
print(F.numpy())

Matrix F:
[[0.91451883 0.23277676 0.5265808 ]
 [0.47189236 0.13738155 0.6517948 ]
 [0.66515386 0.5137708  0.22573543]]


In [12]:
#2. Calculate the transpose of matrix F and store the result in matrix G.

#Ans

import tensorflow as tf

# Create matrix F (3x3) as shown in the previous response
F = tf.random.uniform(shape=(3, 3))

# Calculate the transpose of matrix F
G = tf.transpose(F)

# Display matrix G (transpose of F)
print("Matrix G (Transpose of F):")
print(G.numpy())

Matrix G (Transpose of F):
[[0.37257254 0.3387065  0.06123078]
 [0.21743643 0.9178593  0.04743612]
 [0.36305487 0.5463023  0.80404055]]


In [13]:
#3. Calculate the element-wise exponential of matrix F and store the result in matrix H.

#Ans

import tensorflow as tf

# Create matrix F (3x3) as shown in the previous response
F = tf.random.uniform(shape=(3, 3))

# Calculate the element-wise exponential of matrix F
H = tf.exp(F)

# Display matrix H (element-wise exponential of F)
print("Matrix H (Element-wise Exponential of F):")
print(H.numpy())

Matrix H (Element-wise Exponential of F):
[[2.6706696 1.1610814 1.1938536]
 [1.7516669 1.0206751 2.5792398]
 [1.301145  1.2565585 1.0002519]]


In [14]:
#4. Create a matrix | by concatenating matrix F and matrix G horizontally.

#Ans

import tensorflow as tf

# Create matrix F (3x3) and matrix G (transpose of F) as shown in previous responses
F = tf.random.uniform(shape=(3, 3))
G = tf.transpose(F)

# Concatenate matrices F and G horizontally
H = tf.concat([F, G], axis=1)

# Display matrix H (concatenation of F and G horizontally)
print("Matrix H (Concatenation of F and G Horizontally):")
print(H.numpy())

Matrix H (Concatenation of F and G Horizontally):
[[0.890275   0.50473547 0.673509   0.890275   0.4427836  0.38239205]
 [0.4427836  0.40588307 0.6189853  0.50473547 0.40588307 0.07898736]
 [0.38239205 0.07898736 0.8521795  0.673509   0.6189853  0.8521795 ]]


In [20]:
#5. Create a matrix J by concatenating matrix F and matrix H vertically.

#Ans

import tensorflow as tf

# Create matrix F (3x3) and matrix H (concatenation of F and G horizontally) as shown in previous responses
F = tf.random.uniform(shape=(3, 3))
G = tf.transpose(F)
H = tf.concat([F, G], axis=1)

# Ensure that F and H have the same number of rows for vertical concatenation
# You can create a new matrix with the same number of columns as H
I = tf.random.uniform(shape=(3, 6), dtype=tf.float32)

# Concatenate matrices F and I vertically
J = tf.concat([F, I], axis=1)  # Concatenate along the columns (axis=1)

# Display matrix J (concatenation of F and I vertically)
print("Matrix J (Concatenation of F and I Vertically):")
print(J.numpy())

Matrix J (Concatenation of F and I Vertically):
[[0.8565111  0.7438078  0.8595668  0.68360555 0.8710916  0.572091
  0.42082155 0.97318935 0.9869746 ]
 [0.51872694 0.05810118 0.8278198  0.17824662 0.8816862  0.84047997
  0.0639478  0.91130805 0.13997447]
 [0.18922377 0.975158   0.78516686 0.6994957  0.8484235  0.56102073
  0.76005983 0.93330085 0.24871147]]
